CREATE DATABASE CREDITDB
GO

USE CREDITDB
GO

CREATE TABLE CLIENTE(
	ID BIGINT IDENTITY PRIMARY KEY NOT NULL,
	UID UNIQUEIDENTIFIER UNIQUE NOT NULL,
	CPF NCHAR(14) UNIQUE NOT NULL,
	NOME NVARCHAR(100) NOT NULL,
	UF NCHAR(2) NOT NULL,
	CELULAR NCHAR(15) NOT NULL
)
GO

CREATE TABLE FINANCIAMENTO(
	ID BIGINT IDENTITY PRIMARY KEY NOT NULL,
	UID UNIQUEIDENTIFIER NOT NULL,
	TIPO_FINANCIAMENTO NCHAR(1) NOT NULL CHECK(TIPO_FINANCIAMENTO IN ('D', 'C', 'J', 'F', 'I')),
	VALOR_TOTAL DECIMAL(16, 2) NOT NULL CHECK(VALOR_TOTAL > 0),
	DATA_ULTIMO_VENCIMENTO DATETIME2 NOT NULL,
	CLIENTE_ID BIGINT NOT NULL
)
GO

ALTER TABLE FINANCIAMENTO WITH CHECK ADD CONSTRAINT FK_FINANCIAMENTO_CLIENTE 
FOREIGN KEY(CLIENTE_ID) REFERENCES CLIENTE(ID)
ON UPDATE CASCADE
ON DELETE CASCADE
GO

CREATE TABLE PARCELA(
	ID BIGINT IDENTITY PRIMARY KEY NOT NULL,
	UID UNIQUEIDENTIFIER NOT NULL,
	NUMERO_PARCELA SMALLINT NOT NULL,
	VALOR_PARCELA DECIMAL(16, 2) NOT NULL,
	DATA_VENCIMENTO DATETIME2 NOT NULL,
	DATA_PAGAMENTO DATETIME2 NULL,
	FINANCIAMENTO_ID BIGINT NULL
)
GO

ALTER TABLE PARCELA WITH CHECK ADD CONSTRAINT FK_PARCELA_FINANCIAMENTO 
FOREIGN KEY(FINANCIAMENTO_ID) REFERENCES FINANCIAMENTO(ID)
ON UPDATE CASCADE
ON DELETE CASCADE
GO