CREATE DATABASE CREDITDB
GO

USE CREDITDB
GO

CREATE TABLE CLIENTE(
	ID BIGINT IDENTITY PRIMARY KEY NOT NULL,
	UID UNIQUEIDENTIFIER UNIQUE NOT NULL,
	CPF NCHAR(14) UNIQUE NOT NULL,
	NOME NVARCHAR(100) NOT NULL,
	UF NCHAR(2) NOT NULL,
	CELULAR NCHAR(15) NOT NULL
)
GO

CREATE TABLE FINANCIAMENTO(
	ID BIGINT IDENTITY PRIMARY KEY NOT NULL,
	UID UNIQUEIDENTIFIER NOT NULL,
	TIPO_FINANCIAMENTO NCHAR(1) NOT NULL CHECK(TIPO_FINANCIAMENTO IN ('D', 'C', 'J', 'F', 'I')),
	VALOR_TOTAL DECIMAL(16, 2) NOT NULL CHECK(VALOR_TOTAL > 0),
	DATA_ULTIMO_VENCIMENTO DATETIME2 NOT NULL,
	CLIENTE_ID BIGINT NOT NULL
)
GO

ALTER TABLE FINANCIAMENTO WITH CHECK ADD CONSTRAINT FK_FINANCIAMENTO_CLIENTE 
FOREIGN KEY(CLIENTE_ID) REFERENCES CLIENTE(ID)
ON UPDATE CASCADE
ON DELETE CASCADE
GO

CREATE TABLE PARCELA(
	ID BIGINT IDENTITY PRIMARY KEY NOT NULL,
	UID UNIQUEIDENTIFIER NOT NULL,
	NUMERO_PARCELA SMALLINT NOT NULL,
	VALOR_PARCELA DECIMAL(16, 2) NOT NULL,
	DATA_VENCIMENTO DATETIME2 NOT NULL,
	DATA_PAGAMENTO DATETIME2 NULL,
	FINANCIAMENTO_ID BIGINT NULL
)
GO

ALTER TABLE PARCELA WITH CHECK ADD CONSTRAINT FK_PARCELA_FINANCIAMENTO 
FOREIGN KEY(FINANCIAMENTO_ID) REFERENCES FINANCIAMENTO(ID)
ON UPDATE CASCADE
ON DELETE CASCADE
GO

CREATE PROCEDURE SP_CLIENTE_INSERT
    (@Uid UNIQUEIDENTIFIER,
     @Cpf NCHAR(14),
	 @Nome NVARCHAR(100),
	 @Uf NCHAR(2),
	 @Celular NCHAR(15))    
AS    
BEGIN    
    INSERT INTO CLIENTE (
        UID, 
        CPF, 
        NOME, 
        UF, 
        CELULAR
    ) VALUES (
        @Uid,
        @Cpf,
        @Nome,
        @Uf,
        @Celular
    )

    SELECT SCOPE_IDENTITY()
END
GO

CREATE PROCEDURE SP_CLIENTE_UPDATE
    (@Id BIGINT,
     @Cpf NCHAR(14),
	 @Nome NVARCHAR(100),
	 @Uf NCHAR(2),
	 @Celular NCHAR(15))    
AS    
BEGIN    
    UPDATE CLIENTE SET
        CPF = @Cpf, 
        NOME = @Nome, 
        UF = @Uf, 
        CELULAR = @Uf
    WHERE ID = @Id
END
GO

CREATE PROCEDURE SP_CLIENTE_DELETE
    (@Id BIGINT)    
AS    
BEGIN    
    DELETE CLIENTE
    WHERE ID = @Id
END
GO

CREATE PROCEDURE SP_FINANCIAMENTO_INSERT
    (@Uid UNIQUEIDENTIFIER,
	 @TipoFinanciamento CHAR(1),
	 @ValorTotal DECIMAL(18, 2),
	 @DataUltimoVencimento DATETIME2,
	 @ClienteId BIGINT)
AS    
BEGIN    
    INSERT INTO FINANCIAMENTO (
	    UID,
	    TIPO_FINANCIAMENTO,
	    VALOR_TOTAL,
	    DATA_ULTIMO_VENCIMENTO,
	    CLIENTE_ID
    ) VALUES (
	    @Uid,
	    @TipoFinanciamento,
	    @ValorTotal,
	    @DataUltimoVencimento,
	    @ClienteId
    )

    SELECT SCOPE_IDENTITY()
END
GO

CREATE PROCEDURE SP_PARCELA_INSERT
    (@Uid UNIQUEIDENTIFIER,
	 @NumeroParcela SMALLINT,
	 @ValorParcela DECIMAL(18, 2),
	 @DataVencimento DATETIME2,
	 @FinanciamentoId BIGINT)
AS    
BEGIN    
    INSERT INTO PARCELA (
	    UID,
	    NUMERO_PARCELA,
	    VALOR_PARCELA,
	    DATA_VENCIMENTO,
	    FINANCIAMENTO_ID
    ) VALUES (
	    @Uid,
	    @NumeroParcela,
	    @ValorParcela,
	    @DataVencimento,
	    @FinanciamentoId
    )

    SELECT SCOPE_IDENTITY()
END
GO