SELECT 
	CLI.CPF, 
	CLI.NOME,
	(SUM(PAR.VALOR_PARCELA) / FIN.VALOR_TOTAL * 100) PORCENTAGEM_PAGA
FROM CLIENTE CLI
INNER JOIN FINANCIAMENTO FIN
	ON FIN.CLIENTE_ID = CLI.ID
INNER JOIN PARCELA PAR
	ON PAR.FINANCIAMENTO_ID = FIN.ID
		AND PAR.DATA_PAGAMENTO IS NOT NULL
WHERE CLI.UF = 'SP'
GROUP BY 
	CLI.CPF, 
	CLI.NOME,
	FIN.VALOR_TOTAL
HAVING (SUM(PAR.VALOR_PARCELA) / FIN.VALOR_TOTAL) > 0.6

SELECT TOP 4 
	CLI.CPF, 
	CLI.NOME 
FROM CLIENTE CLI
INNER JOIN FINANCIAMENTO FIN
	ON FIN.CLIENTE_ID = CLI.ID
INNER JOIN PARCELA PAR
	ON PAR.FINANCIAMENTO_ID = FIN.ID
		AND PAR.DATA_VENCIMENTO > DATEADD(DAY, 5, GETDATE())
		AND PAR.DATA_PAGAMENTO IS NULL
GROUP BY 
	CLI.CPF, 
	CLI.NOME